services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run start
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
